server {
  listen 80;
  server_name www.dsp5-archi-f24a-15m-g3.fr localhost;

  # Redirection automatique vers HTTPS
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name www.dsp5-archi-f24a-15m-g3.fr localhost;

  ssl_certificate /etc/letsencrypt/live/dsp5-archi-f24a-15m-g3.fr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/dsp5-archi-f24a-15m-g3.fr/privkey.pem;
  
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}
