# Serveur HTTP (redirection vers HTTPS)
server {
    listen 8081;
    server_name www.dsp5-archi-f24a-15m-g3.fr localhost;

    # Redirection automatique vers HTTPS
    return 301 https://$host$request_uri;
}

# Serveur HTTPS
server {
    listen 443 ssl;
    server_name www.dsp5-archi-f24a-15m-g3.fr localhost;

    ssl_certificate /etc/letsencrypt/live/dsp5-archi-f24a-15m-g3.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dsp5-archi-f24a-15m-g3.fr/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:...';

    root /usr/share/nginx/html;
    index index.html;

    # Configuration des routes pour le frontend
    location / {
        try_files $uri /index.html;
    }
}
