# Étape 1 : build & test
FROM node:22-slim AS builder

WORKDIR /app

COPY package.json .  
COPY package-lock.json . 

# Mettre à jour les dépôts et installer les dépendances nécessaires
RUN apt-get update && apt-get install -y libssl3 libcurl4 apt-utils curl git ca-certificates gnupg

RUN npm ci

COPY . .

RUN npm run test

# Étape 2 : image finale
FROM node:22-slim

WORKDIR /app

COPY package.json . 
COPY package-lock.json . 

# Installer les dépendances, sans les devDependencies pour l'image finale
RUN npm ci --omit=dev

COPY . .

CMD ["node", "server.js"]
