# Identifiant unique du projet
sonar.projectKey=thetiptop_game

# Nom du projet (optionnel mais recommandé)
sonar.projectName=TheTipTop Game Backend

# Langage principal
sonar.language=js

# Dossier racine du code source
sonar.sources=.

# Dossiers à exclure de l’analyse (tests par exemple)
sonar.exclusions=tests/**

# Répertoire contenant les fichiers de test
sonar.tests=tests

# Rapport de couverture généré (si tu utilises Jest avec --coverage)
sonar.coverage.exclusions=**/*.test.js
sonar.testExecutionReportPaths=coverage/test-report.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Adresse du serveur SonarQube
sonar.host.url=https://www.sonarqube.dsp5-archi-f24a-15m-g3.fr

# Auth via token (sera injecté en ligne de commande dans Jenkins)
# sonar.token=*** (on le met via Jenkins)
